using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 

namespace BDAutoMuxer.controllers
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    


    public partial class XMLChapters
    {

        private ChaptersChapterAtom[] editionEntryField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ChapterAtom", IsNullable = false)]
        public ChaptersChapterAtom[] EditionEntry
        {
            get
            {
                return this.editionEntryField;
            }
            set
            {
                this.editionEntryField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ChaptersChapterAtom
    {

        private System.String chapterTimeStartField;

        private ChaptersChapterAtomChapterDisplay chapterDisplayField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "time")]
        public System.String ChapterTimeStart
        {
            get
            {
                return this.chapterTimeStartField;
            }
            set
            {
                this.chapterTimeStartField = value;
            }
        }

        /// <remarks/>
        public ChaptersChapterAtomChapterDisplay ChapterDisplay
        {
            get
            {
                return this.chapterDisplayField;
            }
            set
            {
                this.chapterDisplayField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ChaptersChapterAtomChapterDisplay
    {

        private string chapterStringField;

        private string chapterLanguageField;

        /// <remarks/>
        public string ChapterString
        {
            get
            {
                return this.chapterStringField;
            }
            set
            {
                this.chapterStringField = value;
            }
        }

        /// <remarks/>
        public string ChapterLanguage
        {
            get
            {
                return this.chapterLanguageField;
            }
            set
            {
                this.chapterLanguageField = value;
            }
        }
    }
}
